Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -25,13 +25,16 @@ jobs:
           CLIENT_SECRET: ${{ secrets.MULESOFT_CLIENT_SECRET }}
         run: |
           RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
-          https://anypoint.mulesoft.com/accounts/api/v2/oauth2/t oken \
-          -H 'Content-Type: application/x-www-form-urlencoded' \
-          -d 'client_id='${{ secrets.MULESOFT_CLIENT_ID }}'&client_secret='${{ secrets.MULESOFT_CLIENT_SECRET }}'&grant_type=client_credentials')
+          "https://anypoint.mulesoft.com/accounts/api/v2/oauth2/token" \
+          -H "Content-Type: application/x-www-form-urlencoded" \
+          -d "client_id=${CLIENT_ID}&client_secret=${CLIENT_SECRET}&grant_type=client_credentials")
+
           if [ "$RESPONSE" != "200" ]; then
-             echo "Error: Failed to obtain Anypoint Platform access token. Response code: $RESPONSE"
-             exit 1
+            echo "Error: Failed to obtain Anypoint Platform access token. Response code: $RESPONSE"
+            exit 1
           fi
+
+           echo "Anypoint Platform access token obtained successfully."
       - name: Publish Asset to Exchange
         env:
           ANYPOINT_TOKEN: ${{ secrets.ANYPOINT_TOKEN }}
