Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -97,12 +97,12 @@ jobs:
               --form 'name="file"' \
               --form 'filename=@./proxyhttpapi-v1.zip' | jq -r '.id')
               echo "API created in API Manager with ID $api_id"
-          if [ -z "$api_id" ]; then
-             echo "Error: Failed to create API in API Manager. "
-             exit 1
-           fi
-          echo "API created in API Manager with ID ${api_id}"
-            echo "${api_id}" > ./api_id.txt
+              if [ -z "$api_id" ]; then
+                echo "Error: Failed to create API in API Manager. "
+                exit 1
+              fi
+              echo "API created in API Manager with ID ${api_id}"
+              echo "${api_id}" > ./api_id.txt
           fi      
       - name: Commit API ID file to repo
         run: |
