Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -95,7 +95,11 @@ jobs:
               --header 'Authorization: Bearer 0e88033a-be36-4a37-b755-47400e7afb41' \
               --form 'Content-Type="application/zip"' \
               --form 'name="file"' \
-              --form 'file=@./proxyhttpapi-v1.zip' | jq -r '.id')
+              --form 'filename=@./proxyhttpapi-v1.zip' | jq -r '.id')
+          if [ ${api_id} = "" ]; then
+             echo "Error: Failed to create API in API Manager. "
+             exit 1
+           fi
           echo "API created in API Manager with ID ${api_id}"
             echo "${api_id}" > ./api_id.txt
           fi      
